version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    command: > 
      sh -c "python manage.py migrate &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env.prod
    expose:
      - 8000
    volumes:
      - ./staticfiles:/home/python/app/staticfiles
      - ./media:/home/python/app/mediafiles
    depends_on:
      db:
        condition: service_healthy
    links:
      - 'mailhog'
  db:
    container_name: db
    image: postgres:alpine
    volumes:
      - ./.database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - LC_ALL=C.UTF-8
    env_file:
      - .env.prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 3s
      retries: 10
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    restart: always
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./staticfiles:/home/python/app/staticfiles
      - ./media:/home/python/app/mediafiles
    depends_on:
      - app