# Generated by Django 4.1.7 on 2023-03-02 05:07

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('vacancies', models.PositiveSmallIntegerField()),
                (
                    'modality',
                    models.CharField(
                        choices=[
                            ('P', 'presencial'),
                            ('R', 'remoto'),
                            ('H', 'híbrido'),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    'salary',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.0'),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal('0.0')
                            )
                        ],
                    ),
                ),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=500)),
                (
                    'hierarchy',
                    models.CharField(
                        choices=[
                            ('JA', 'Jovem Aprendiz'),
                            ('EST', 'Estágio'),
                            ('A', 'Auxiliar'),
                            ('JR', 'Júnior'),
                            ('P', 'Pleno'),
                            ('S', 'Sênior'),
                            ('ESP', 'Especialista'),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    'experience',
                    models.SmallIntegerField(
                        choices=[
                            (0, 'Nenhuma'),
                            (1, '0 - 1 ano'),
                            (2, '1 - 2 anos'),
                            (3, '2 - 5 anos'),
                            (4, '5 - 10 anos'),
                            (5, 'Mais de 10 anos'),
                        ]
                    ),
                ),
                (
                    'address',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='address.address',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='job.category',
                    ),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='account.profilecompany',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=100)),
                (
                    'job',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sections',
                        to='job.job',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('item', models.CharField(max_length=150)),
                (
                    'section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='itens',
                        to='job.section',
                    ),
                ),
            ],
        ),
    ]
