# Generated by Django 4.1.6 on 2023-02-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_candidate',
            field=models.BooleanField(
                default=False, verbose_name='candidate status'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='is_company',
            field=models.BooleanField(
                default=False, verbose_name='company status'
            ),
        ),
    ]
